### ISSUE TITLE
change type of class

### ISSUE THREAD

**Issue by mhimehdi** [CryptoKass/NoobChain-Tutorial-Part-2#1]
https://github.com/CryptoKass/NoobChain-Tutorial-Part-2/blob/4fd742fd13f7dc991985e68470847ce178b5ab8c/src/noobchain/StringUtil.java#L7

instead of using static methods try to use a singleton 

thank you for  considering my previous issue 👍 

by the way, would you report more information in the wiki please 
MHI

**Comment by CryptoKass** [comment]
Thanks again mhimehdi :) , I will definitely use singletons down the line, but StringUtil has no state (and will have no state), for this reason static method seems a better fit. 

Most the information is reported in the tutorial on medium: [tutorial](https://medium.com/programmers-blockchain/creating-your-first-blockchain-with-java-part-2-transactions-2cdac335e0ce).

However I will create a wiki for the final part :) 👍
