### ISSUE TITLE
BouncyCastle in NoobChain shows error for no reason 

### ISSUE THREAD

**Issue by aabaja11** [CryptoKass/NoobChain-Tutorial-Part-2#7]
I have renamed the "NoobChain" class to "Coding4Life". That's all, but for some reason it highlights bouncy castle as an error. I attached a screenshot of the code. If anybody could assist me that would be great!

Thank you 

<img width="1265" alt="screen shot 2018-03-20 at 12 00 37 pm" src="https://user-images.githubusercontent.com/10700069/37650807-5b038af2-2c36-11e8-8bdc-1db31aff7bfd.png">

**Comment by CryptoKass** [comment]
Have you imported the bouncy-castle library ?

**Comment by aabaja11** [comment]
Yeah sorry I just did it works now thank you! But I’m having issues with
Base64 for some reason. Any idea to what it could be ?

Thank you
